-- SPDX-License-Identifier: MIT

-- Rare intrusive-thought lines from intrusive-thoughts-voice-lines.md.
-- Keep wording and rough/clean pairs in sync with that authored source.
SurvivorCompanion = SurvivorCompanion or {}
SurvivorCompanion.IntrusiveLines = {
["banter.intrusive.travel"] = {
    common = {
        -- Urges, reported and refused
        { "Strong urge to ring every goddamn doorbell in this county. Ignoring it.", clean = "Strong urge to ring every doorbell in this county. Ignoring it." },
        "Part of me wants to yell hello into the next quiet house.",
        "I keep wanting to check the mail. Nobody is sending any.",
        { "Brain says honk the horn of the next car. Brain is fired. Dumbass brain.", clean = "Brain says honk the horn of the next car we pass. Brain is fired." },
        "Had the urge to wave at one of them. Like a neighbour. Didn't.",
        "Some small voice wants me to lie down on the next road. Just because.",
        "Thought about whistling. Then thought about who would answer.",
        "I want to knock on a door and ask for a cup of sugar.",
        "Urge to skip. Full skipping. I am suppressing it professionally.",
        "I want to start a rumour. There's nobody left to tell.",
        -- Doubts and loops
        "Did I lock my front door back home? Does it matter? It matters.",
        { "I never returned a library book. That fine is enormous as hell now.", clean = "I never returned a library book. That fine is enormous now." },
        "I keep counting my steps. Four hundred and something. Lost it.",
        { "Same damn jingle in my head for three miles. Make it stop.", clean = "Same jingle in my head for three miles. Make it stop." },
        "Did I feed the cat before all this? I never had a cat.",
        "Who was the last person to vacuum in Kentucky? I need to know.",
        "Deja vu. Have we walked exactly this way before?",
        "Strong feeling I've said this before. Have I said this before?",
        -- Deadpan observations
        "Every mailbox out here is still waiting for good news.",
        "Somewhere a speed trap is still waiting for a speeder.",
        "Every lawn in Knox County is one week from becoming a meadow.",
        "Nobody has jaywalked in weeks. Civic pride, maybe.",
        "Funny how a road still feels like it's going somewhere.",
        "The last traffic ticket in Kentucky is already written. Unpaid.",
        "Somewhere there's a winning lottery ticket nobody will cash.",
        "I bet the last thing on every radio was a weather report.",
        "The county has never been this quiet, or this crowded.",
        { "Good news: no more traffic. Bad news: every other goddamn thing.", clean = "Good news: no more traffic. Bad news: everything else." },
        -- What-ifs
        "What if the dead are just very, very late for work.",
        "Imagine one of them stops, checks a watch, and keeps going.",
        "I keep picturing one of them doing its taxes. It fits, somehow.",
        { "What if the Army comes back and hands out parking tickets. Bastards would, too.", clean = "What if the Army comes back and just hands out parking tickets." },
        "Picture the census taker this year. Brave soul.",
        "What if Fort Knox is fine and nobody told us.",
        "I just pictured a marching band of the dead. In step, even.",
        "What if they remember the way home better than we do.",
        "If one trips in the woods and nobody hears it, it still gets up.",
        -- Kentucky
        "Thinking about Derby Day. Big hats. Now we wear whatever stops a bite.",
        { "Bourbon ages better than people. Hell, bourbon ages better than anything.", clean = "Bourbon ages better than people, it turns out." },
        "Somewhere a bluegrass band is still in tune. Nobody to hear it.",
        { "One more damn tobacco barn and I'm taking up farming out of spite.", clean = "One more tobacco barn and I'm taking up farming out of spite." },
        "Louisville is still out there being Louisville, with nobody in it.",
        -- Dark
        "Brain keeps asking what I'd look like as one of them. Taller, probably.",
        { "Every ditch out here was somebody's last shitty idea.", clean = "Every ditch out here was somebody's last idea." },
        "I wonder which of them said the last good morning in Kentucky.",
        { "The dead never get tired. That's bullshit, is what that is.", clean = "The dead never get tired. That's not fair, is it." },
        "I keep picturing my own body by a road. Badly dressed.",
        "What if I'm already scratched and haven't noticed. Checked. Fine. Checking again.",
        { "Morbid thought: the goddamn crows are eating better than we are.", clean = "Morbid thought: the crows are eating better than we are." },
        "Some days I envy them. No hunger. No choices. No sore feet.",
        "The roadside is lined with people who also had a plan.",
        { "If I go down out here, take the boots. They're damn good boots.", clean = "If I go down out here, take the boots. They're good boots." },
        "I keep drawing up a will in my head. You get the can opener.",
        "Every step is one fewer. My brain does that math unasked.",
        -- Rough
        { "My feet hurt, my back hurts, and the world ended. Shit week.", clean = "My feet hurt, my back hurts, and the world ended. Rough week." },
        { "Kentucky's still pretty. Pretty as hell, and full of dead folks.", clean = "Kentucky's still pretty. Pretty as anything, and full of dead folks." },
        { "Another mile. Another goddamn mile. Then probably another one.", clean = "Another mile. Another darn mile. Then probably another one." },
        { "Somewhere a preacher is still telling corpses to repent. Good fucking luck.", clean = "Somewhere a preacher is still telling corpses to repent. Good luck with that." },
        { "I'd kill for a goddamn cigarette. Bad choice of words. Still true.", clean = "I'd kill for a cigarette. Bad choice of words. Still true." },
    },
    brave = {
        { "Urge to challenge the next one to arm wrestling. I'd kick its ass.", clean = "Urge to challenge the next one to arm wrestling. I'd win." },
        "I keep wanting to kick in doors I could just open.",
        { "Brain suggests a war cry. Brain has never given a damn about consequences.", clean = "Brain suggests a war cry. Brain has never considered consequences." },
        { "Sometimes I want to shout my name at the whole damn county.", clean = "Sometimes I want to shout my name at the whole county." },
        "I keep thinking the next fight will be the good story.",
        "Part of me wants to walk the middle of the road like I own it.",
        { "Come on out, you rotten sons of bitches. I'm in a mood.", clean = "Come on out, you rotten varmints. I'm in a mood." },
    },
    cautious = {
        "I counted the exits out here. There aren't any. I counted anyway.",
        "What if every closed door is closed for a reason.",
        "I keep checking behind us. The way back is still there. Good.",
        { "That kind of quiet is exactly the kind I don't trust. Hell no.", clean = "That kind of quiet is exactly the kind I don't trust." },
        "I double-checked my pockets. Then I triple-checked them.",
        "My brain keeps drawing the map, then a second map, just in case.",
    },
    caring = {
        "I keep wondering if they're cold. The dead. Stupid thought.",
        "Every porch we pass, I wonder who used to sit on it.",
        "Sometimes I wave at windows. In case someone's still home.",
        "I hope somebody fed the dogs. Every dog. All of them.",
        { "Weird thought: I miss strangers. Ordinary, rude, living sons of bitches.", clean = "Weird thought: I miss strangers. Ordinary, rude, living strangers." },
        "I keep wanting to leave notes on doors. We came by, you weren't home.",
    },
    practical = {
        "Running inventory in my head again. It never adds up to enough.",
        "A shopping cart is a vehicle if you believe hard enough.",
        "I keep working out how many cans fit in a mailbox. Several.",
        "Every abandoned car is just a very heavy cabinet now.",
        { "Mental note: the end of the world has shitty signage.", clean = "Mental note: the end of the world has terrible signage." },
        "I priced the next mile in batteries. It's cheap.",
        { "Ran the numbers on this trip. The numbers say we're fucked. Walk faster.", clean = "Ran the numbers on this trip. The numbers say we're screwed. Walk faster." },
    },
    steady = {
        "Weird thought just arrived. It can walk with us a while.",
        "Another stray thought. It'll leave when it gets bored.",
        "My head's doing that thing again. Ignore me.",
        "Thought of something odd. Filing it under later.",
        "Brain just said what if. I told it not now.",
    },
    stressed = {
        "I keep picturing the worst version of every corner.",
        { "Thought loop again. Same corner, same ending. Make it stop, goddammit.", clean = "Thought loop again. Same corner, same ending. Make it stop." },
        { "My head keeps narrating how we die. Shitty writing, too.", clean = "My head keeps narrating how we die. Badly written, too." },
        "Every sound turns into a story in my head. None are happy.",
        "I keep thinking we left someone behind. Count us again.",
        { "Oh God. Oh shit. Nothing happened. I just felt like saying it.", clean = "Oh God. Oh no. Nothing happened. I just felt like saying it." },
    },
    low = {
        { "The road doesn't give a damn if we make it. Neither does the sky.", clean = "The road doesn't care if we make it. Neither does the sky." },
        "Sometimes the quiet sounds like the world holding its breath.",
        "A song from before keeps playing in my head. It hurts a little.",
        "Every empty car had someone who meant to come back.",
        "My head's full of rooms nobody will walk into again.",
        { "Whole damn county, and not one person left to wave at.", clean = "Whole county, and not one person left to wave at." },
    },
    hopeful = {
        "Someday someone will drive the next road just for fun.",
        "I keep picturing a diner reopening. Pie and everything.",
        "What if one day all this is just a story we tell badly.",
        "I keep thinking the radio will play real music again.",
        "Sometimes I plan a garden in my head. Rows and rows.",
    },
},

["banter.intrusive.camp"] = {
    common = {
        -- Urges, reported and refused
        "I want to sort all the cans by colour. I'm resisting.",
        "Sudden urge to sweep the whole place at midnight.",
        "Part of me wants to paint the walls bright yellow. Unwarranted.",
        { "Strong urge to ring a dinner bell. We don't have a damn dinner bell.", clean = "Strong urge to ring a dinner bell. We don't have a dinner bell." },
        "I keep wanting to answer a phone that isn't ringing.",
        "Urge to knock on the wall to see if anything knocks back. No.",
        "Every so often I want to throw a party. For whom, exactly.",
        "I want to stack every chair in here into something tall.",
        -- Doubts and loops
        "Did I lock the door? I locked the door. I'll check the door.",
        { "I counted the cans twice and got two different goddamn answers.", clean = "I counted the cans twice and got two different answers." },
        "Was it always this quiet in here? It was. Probably.",
        "I just realised I don't know what day it is. Tuesday feels right.",
        "If I alphabetise the pantry, does that count as progress.",
        "Strong feeling we've had this exact evening before.",
        { "I keep rehearsing an argument from 1989. I was right, dammit.", clean = "I keep rehearsing an argument from 1989. I was right." },
        -- Deadpan observations
        "We're the neighbours now. Somebody's bad neighbours.",
        "This camp has a better retirement plan than my old job.",
        "Every place was somebody's camp once. This one's ours. For now.",
        "We have more rules than the county council ever did.",
        "I think this place liked its old owners better.",
        "Quiet nights here sound exactly like waiting.",
        "Our security is better than any bank in Muldraugh. Was.",
        "Property listing: secure, quiet, some neighbours dead. Make an offer.",
        -- What-ifs
        "What if a salesman knocks. What do we even say.",
        "Picture the mailman showing up. I'd hug him. Then check for bites.",
        "I keep imagining a home inspector walking through here.",
        "What if someone left us a fruit basket. Welcome to the end.",
        "What if the place is haunted and the ghost is just annoyed.",
        "Dreamt they formed a neighbourhood watch. Very strict about lawns.",
        "Imagine explaining this camp to someone from 1992.",
        "What if the dead just want to sit in a nice chair too.",
        -- Kentucky and life before
        "I'd trade a week of cans for one plate of real fried chicken.",
        "I keep thinking about church potlucks. Every casserole. Every one.",
        "Somewhere there's a Derby pie with my name on it. Expired.",
        { "I'd fight a horde for a glass of sweet tea. A small damn horde.", clean = "I'd fight a horde for a glass of sweet tea. A small horde." },
        "A porch, a rocking chair, nothing happening. That was luxury.",
        { "Somebody in Kentucky still owes me five bucks. Son of a bitch.", clean = "Somebody in Kentucky still owes me five dollars. Unlikely now." },
        -- Dark
        "Every bed here belonged to someone who expected to wake up in it.",
        { "If we die here, some bastard just loots this place. Like we did.", clean = "If we die here, this place is just somebody else's loot." },
        "I keep picturing the walls failing at three in the morning. Exactly three.",
        "Sometimes I wonder which of us goes first. Don't look at me.",
        "We should write our names somewhere. For whoever finds us.",
        "We'd make a very well-organised ghost town.",
        "I keep thinking about their last meal here. Whoever they were.",
        "If I go bad, put me down before I ruin the pantry.",
        "Every quiet evening feels borrowed. The interest will be terrible.",
        "Morbid inventory: shovels, two. Graves dug, more than two.",
        "I counted us this morning. I count us every morning now.",
        { "This place will outlast us. It's a real smug bastard about it, too.", clean = "This place will outlast us. It's rude about it, too." },
        -- Rough
        { "Who keeps leaving the goddamn door open? Oh. It's me. It was me.", clean = "Who keeps leaving the door open? Oh. It's me. It was me." },
        { "Somebody snores like a goddamn chainsaw. Not naming names. It's you.", clean = "Somebody snores like a chainsaw. Not naming names. It's you." },
        { "Peace and quiet. Christ, I hate peace and quiet now.", clean = "Peace and quiet. Lord, I hate peace and quiet now." },
        { "Home sweet hellhole. Pass the beans.", clean = "Home sweet home. Pass the beans." },
    },
    brave = {
        { "Sometimes I want to open the gate and shout come on, you bastards.", clean = "Sometimes I want to open the gate and shout come on, then." },
        "Urge to sleep on the roof. Under the stars. Armed.",
        "I keep wanting to build a watchtower. A really big one.",
        "The walls make me feel caged, not safe. Odd thought.",
        "I keep planning raids on places we don't need to raid.",
        "What if I challenged the whole night to a fair fight.",
        { "Let them come. I sharpened everything. Twice. Even the damn spoons.", clean = "Let them come. I sharpened everything. Twice. Even the spoons." },
    },
    cautious = {
        "I've counted the ways in three times. Still the same number.",
        { "What if the barricade's fine and I'm the weak goddamn point.", clean = "What if the barricade is fine and I'm the weak point." },
        "Every door in here is one door too many.",
        "I keep picturing this place from the outside. Not comforting.",
        "Did anyone check the back? I'll check the back.",
        "I listen to the place settle and give every creak a name.",
    },
    caring = {
        "I keep wondering if everyone ate. Did everyone eat?",
        "This place needs a cat. Someone to look after.",
        "Sometimes I set out an extra plate without meaning to.",
        "I keep wanting to tuck everyone in. Even the brave ones.",
        "I hope the people who lived here got somewhere safe.",
        "I hum lullabies while I work. Habit. Don't tell anyone.",
    },
    practical = {
        "I've redesigned this camp four times in my head today.",
        { "Planks per wall per argument. Still not enough damn planks.", clean = "Planks per wall per argument. Still not enough planks." },
        { "Thought: a moat. Hear me out. A goddamn moat.", clean = "Thought: a moat. Hear me out. A moat." },
        "I keep inventorying things that aren't ours yet.",
        "Every broken chair is firewood with ambition.",
        "I reorganised the shelves in my head. They're better now.",
        { "Fixed the window. Fixed the door. Fixed nothing that actually matters. Shit.", clean = "Fixed the window. Fixed the door. Fixed nothing that actually matters. Oh well." },
    },
    steady = {
        "Odd thought came through. I let it sit a while.",
        "My brain's doing housework of its own. Let it.",
        "Had a strange thought. It was polite. It left.",
        "My mind wandered off and came back with nothing useful.",
        "Just a passing notion. I'm not charging it rent.",
    },
    stressed = {
        "I keep hearing knocking that isn't there. Isn't it?",
        "Every night I rebuild the walls in my head. Thicker.",
        { "What if this is the night. I think that every damn night.", clean = "What if this is the night. I think that every night." },
        "My brain keeps rehearsing the worst evening. Over and over.",
        "I can't stop listening for footsteps that aren't ours.",
    },
    low = {
        "This place remembers more people than it holds.",
        "Some nights the quiet sounds like everyone who's gone.",
        "I keep folding clothes for people who aren't coming back.",
        "We're keeping a museum nobody visits.",
        "The dishes stay clean now. Nobody's here to dirty them.",
    },
    hopeful = {
        "One day this camp gets a sign. A proper painted one.",
        "I keep imagining a garden party here. With tablecloths.",
        "Someday kids will grow up here and think it's normal. And fine.",
        "I just planned a whole holiday dinner in my head.",
        "Someday this is just the old place. I'd like that.",
    },
},

["banter.intrusive.dark"] = {
    common = {
        "Sometimes I want to stop running just to see what happens. I don't.",
        "One bad step and I'm the thing we're running from.",
        { "I keep rehearsing my last words. Mostly they're just oh, shit.", clean = "I keep rehearsing my last words. They're never good enough." },
        "Somewhere there's a version of me that didn't make it. Lucky?",
        "The dead don't remember us. That should help. It doesn't.",
        "My hands remember things I did this summer. I wish they'd stop.",
        "I keep doing the math on how long we last. I stop early.",
        "When you sleep, I check you're breathing. Habit now.",
        "What if this is the good part. What if it gets worse.",
        "The quiet ones in the street were somebody's children.",
        "I dream I'm one of them and it's peaceful. Then I wake up hungry.",
        "We're all just very slow corpses with better manners.",
        "If I go, don't say anything nice. Just take the boots.",
        "Some nights I hear my mother calling. She's been gone for years.",
        { "I keep picturing shoving you at them. Then who'd carry the damn beans.", clean = "I keep picturing shoving you into a crowd of them. Then who'd carry the beans." },
        "Brain suggests you might be the dangerous one. Brain is outvoted.",
        { "I keep wondering if turning hurts. I'd rather not find out. Hell no.", clean = "I keep wondering if it hurts. Turning. I'd rather not find out." },
        { "Someday one of those things will be wearing my face. Son of a bitch.", clean = "Someday one of those things will be wearing my face. Son of a gun." },
        { "We're not surviving. We're just dying slower than the other bastards.", clean = "We're not surviving. We're just dying slower than everybody else." },
        { "If I turn, shoot me quick. Don't make a goddamn speech.", clean = "If I turn, shoot me quick. Don't make a speech." },
    },
    brave = {
        "I keep wanting to walk into the biggest crowd of them and see who blinks.",
        "Some days I want the fight more than I want to win it.",
        { "If I go out, I want it loud. Loud as hell.", clean = "If I go out, I want it loud. Very loud." },
    },
    cautious = {
        "I keep planning who I'd save first. I hate that I know.",
        "Every exit I memorise is one I might use alone.",
        "What if the careful ones just die last. That's the whole prize.",
    },
    caring = {
        "I keep imagining burying each of you. Then I stop. Then I don't.",
        "Sometimes I talk to the people we couldn't save. They don't answer.",
        "I'm getting used to this. That's the part that scares me.",
    },
    practical = {
        "I know exactly how many rounds it would take. For all of us.",
        { "Shoes, water, ammo, will. In that order. Will is running low as shit.", clean = "Shoes, water, ammo, will. In that order. Will is running low." },
        "If I go bad, the pantry key is in my left boot.",
    },
},

["banter.intrusive.night"] = {      -- game hour 21:00 to 05:00
    common = {
        "The stars don't know anything happened.",
        "At night my brain starts a second shift.",
        "Every night I wonder who else is awake out there.",
        { "The dark makes my thoughts louder. Real asshole move, dark.", clean = "The dark makes my thoughts louder. Rude of it." },
        "The world switches off and my head switches on.",
        "Somebody, somewhere, is lying awake about this too.",
        "Midnight math: days survived, cans left, people met.",
        "I keep thinking the night has more of them in it.",
        { "Three in the morning. Every goddamn thought I own is awake.", clean = "Three in the morning. Every thought I own is awake." },
    },
},
["banter.intrusive.rain"] = {       -- raining, speaker outdoors
    common = {
        "The rain is washing a county that doesn't deserve it.",
        "Rain sounds like applause for something I missed.",
        "Every drop is free water. My brain won't stop saying so.",
        { "I want to stand in it like a kid. Like a damn idiot.", clean = "I want to stand in it like a kid. Like an idiot." },
        "Rain makes them look almost sorry.",
        "Smells like a ballgame got rained out. Every game, forever.",
    },
},
["banter.intrusive.seated"] = {     -- sitting on furniture
    common = {
        "Somebody broke this chair in for me. Thank you, stranger.",
        "Sitting down makes my brain stand up.",
        "I keep thinking this chair was somebody's favourite.",
        "If I sit still long enough, maybe the world forgets me too.",
        { "Comfortable. Suspiciously goddamn comfortable.", clean = "Comfortable. Suspiciously comfortable." },
        "I had a recliner once. We were very happy together.",
    },
},

["banter.intrusive.height"] = {     -- floor 2 or higher, or out on a roof
    common = {
        { "Every roof asks the same stupid damn question. I keep saying no.", clean = "Every roof asks the same stupid question. I keep saying no." },
        "Up high, my brain whispers ideas. My legs veto them.",
        { "From up here they look like ants. Hungry little bastards.", clean = "From up here they look like ants. Hungry ants." },
        "I always want to drop something off a roof. Just to watch.",
        "Heights make my thoughts lean over the edge before I do.",
        "Somebody built this high to see trouble coming. Did it help?",
        "Gravity still works. Good to know some rules held.",
        "If I yell from up here, the whole county hears. Tempting. No.",
    },
},
["banter.intrusive.passenger"] = {  -- riding as a passenger, moving
    common = {
        "Urge to grab the wheel. Just a little. I'm sitting on my hands.",
        "I keep wanting to open the door at full speed. I won't.",
        "Every tree we pass, my brain asks what if.",
        "We're a metal box full of snacks, as far as they're concerned.",
        { "I want to hang my arm out the window. Bad goddamn idea out here.", clean = "I want to hang my arm out the window. Bad idea out here." },
        "Car rides used to mean somewhere fun. Now they mean somewhere less bad.",
    },
},
["banter.intrusive.after_kill"] = { -- the speaker's own kill, once clear
    common = {
        "That one used to have a favourite song.",
        "Somebody once taught that one to ride a bike.",
        "I wonder if some part of it knew. I hope not.",
        "That was somebody's plans for Tuesday.",
        { "I'm getting good at this. I'd rather not be. Goddammit.", clean = "I'm getting good at this. I'd rather not be." },
        "It went down like it was tired. Maybe it was.",
        "I keep wanting to say sorry. To them. Is that strange?",
        "One less. I don't feel one better.",
        { "Sorry, buddy. Hell of a way to go. Hell of a way to stay.", clean = "Sorry, buddy. Heck of a way to go. Heck of a way to stay." },
    },
},
["banter.intrusive.grief"] = {      -- speaker is mourning
    common = {
        "I keep saving them a seat. Then I remember.",
        "Thought I heard them laugh just now. My brain is cruel like that.",
        "Nobody's touched their things. Nobody will.",
        { "I keep turning around to tell them something. Goddammit.", clean = "I keep turning around to tell them something." },
        "Part of me thinks they'll walk back in. Part of me is scared they will.",
        "I count us and come up one short. Every time.",
    },
},
["banter.intrusive.hidden_bite"] = { -- hidden, undiscovered bite; never name it
    common = {
        "I keep checking my own pulse. Still there.",
        "My skin feels like it belongs to somebody else today.",
        { "I'm fine. I keep saying it. I'm fine, goddammit.", clean = "I'm fine. I keep saying it. I'm fine." },
        "Is it warm in here, or is it me?",
        "I keep wanting to write some letters. No reason.",
        "What would I do, if it were me. Nothing, probably. Nothing.",
    },
},
["banter.intrusive.night_watch"] = { -- guard shift at night
    common = {
        "Night watch: every shadow gets a name, then a backstory.",
        "The dark isn't watching back. It is, though.",
        "Out here alone, my brain throws a parade of worst cases.",
        "I count stars when I can't stand counting anything else.",
        { "I'm the only damn thing between them and the snoring.", clean = "I'm the only thing between them and the snoring." },
        "If something comes, I'm the first story. Short story.",
    },
},
["banter.intrusive.eating"] = {     -- the speaker is eating
    common = {
        "I keep wondering who stocked this. I hope they got out.",
        "Eating dead people's groceries. Mostly guilt-free.",
        "This tastes like a kitchen that doesn't exist anymore.",
        "Brain says savour it. Brain also says it might be the last.",
        "Somebody bought this for a party, once.",
        "Best meal of the day. Also the worst. Also the only.",
    },
},

["banter.intrusive.place.morgue"] = { common = {
    "Every drawer in here is a bed nobody chose.",
    "Urge to open every drawer. No. Absolutely not.",
} },
["banter.intrusive.place.church"] = { common = {
    "Urge to ring the bell. Everyone would come. That's the problem.",
    "If anyone's still taking prayers, I have a list.",
} },
["banter.intrusive.place.hospital"] = { common = {
    "All this medicine and nobody left to prescribe it.",
    "They ran out of beds. Then they didn't need them.",
} },
["banter.intrusive.place.school"] = { common = {
    "Detention's over. Forever.",
    "I keep picturing the last lesson on the board. Something about the future.",
} },
["banter.intrusive.place.police"] = { common = {
    { "I want to file a report. About every goddamn thing.", clean = "I want to file a report. About everything." },
    "Nobody to arrest, nobody to call. Still feels like trouble in here.",
} },
["banter.intrusive.place.prison"] = { common = {
    "Funny place to feel safe.",
    "The locks held. The people didn't.",
} },
["banter.intrusive.place.bar"] = { common = {
    "Last call was a while ago. Nobody heard it.",
    "Urge to order a drink from nobody. Tipping well.",
} },
["banter.intrusive.place.liquor"] = { common = {
    "Bourbon will outlive everybody. Kentucky planned ahead.",
    "Every bottle in here is somebody's bad decision, saved for later.",
} },
["banter.intrusive.place.pharmacy"] = { common = {
    "Every pill in here was somebody's tomorrow.",
    "Urge to read every label. Side effects may include everything.",
} },
["banter.intrusive.place.gunstore"] = { common = {
    { "Plenty of guns. Never enough sense. Not before, sure as hell not after.", clean = "Plenty of guns. There was never enough sense, before or after." },
    "Everybody in here was ready. It didn't matter.",
} },
["banter.intrusive.place.spiffos"] = { common = {
    "Somewhere in here a mascot costume is still smiling.",
    "Urge to order a kids meal. Toy included.",
} },
["banter.intrusive.place.grocery"] = { common = {
    "Aisle five: denial. Aisle six: canned goods.",
    "I keep wanting to grab a cart. For old times.",
} },
["banter.intrusive.place.gas"] = { common = {
    { "Prices went up. Then everything went to hell.", clean = "Prices went up. Then everything went down." },
    "Urge to buy a lottery ticket. The odds have never been better.",
} },
["banter.intrusive.place.dentist"] = { common = {
    "Even now, I won't sit in that chair.",
    { "End of the world and I still feel guilty about flossing. Bullshit.", clean = "End of the world and I still feel guilty about flossing." },
} },
["banter.intrusive.place.hunting"] = { common = {
    "Everybody's a hunter now. Nobody's a sportsman.",
    "All this camouflage, and the dead found them anyway.",
} },

["banter.intrusive.reply"] = {
    common = {
        "Nobody asked, but thank you.",
        { "Put that goddamn thought back where you found it.", clean = "Put that thought back where you found it." },
        { "That's going to stay with me now. Thanks a lot, asshole.", clean = "That's going to stay with me now. Thanks." },
        "I've had worse ones. Today, actually.",
        "You say these things out loud on purpose.",
        "Noted. Never mention it again.",
        "Same, honestly. Don't tell anyone.",
        "I'm writing that down. As evidence.",
        "Please keep the strange ones to yourself.",
        "That's the most normal thing you've said all week.",
        { "Your head is a scary goddamn neighbourhood.", clean = "Your head is a scary neighbourhood." },
        "I was having a nice quiet minute, too.",
        { "Dark as hell. Accurate, but dark as hell.", clean = "Dark. Accurate, but dark." },
        "You're on dish duty for that one.",
        "Thanks. I'll be thinking about that at three in the morning.",
        "We're all thinking it. You just say it.",
        "That's not an intrusive thought. That's a confession.",
        { "Well, shit. Now I need a drink.", clean = "Well. Now I need a drink." },
        "You need a hobby. Or a nap. Possibly both.",
        "Remind me never to stand next to you on a roof.",
        "Kentucky made you strange. Stranger.",
        "Somewhere a therapist just sat up in bed.",
        { "Christ almighty. Where do you even get these?", clean = "Good grief. Where do you even get these?" },
        { "Shut the hell up. You're right, but shut the hell up.", clean = "Shut up. You're right, but shut up." },
        { "Goddamn, that's grim. Say another one.", clean = "Gosh, that's grim. Say another one." },
    },
    brave = { { "Ha. Hell, I'd do it. Don't let me do it.", clean = "Ha. I'd do it. Don't let me do it." } },
    cautious = { "Let's not test that theory." },
    caring = { "You all right? That one sounded heavy." },
    practical = { "Interesting. Useless, but interesting." },
    steady = { "Mm. Fair enough." },
    stressed = { { "Jesus Christ, please don't. I'm barely holding it together.", clean = "Please don't. I'm barely holding it together." } },
    low = { "Yeah. I think about that too." },
    hopeful = { "I like that one. Keep that one." },
},
}
return SurvivorCompanion.IntrusiveLines
